name: Build declaritive-postgres

on:
  push:
    tags:
      - '18.4_v*'

env:
  IMAGE_NAME: ghcr.io/jptrs93/declaritive-postgres

jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-go@v6.0.0
        with:
          go-version-file: declaritive-postgres/go.mod
      - name: Test Go packages
        run: go test ./...
        working-directory: declaritive-postgres
      - name: Build test image
        run: docker build --platform linux/amd64 -f declaritive-postgres/Dockerfile -t declaritive-postgres:test .
      - name: Run integration test
        run: declaritive-postgres/tests/integration.sh declaritive-postgres:test

  publish:
    needs: test
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: docker/login-action@v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build --platform linux/amd64 -f declaritive-postgres/Dockerfile \
            -t $IMAGE_NAME:$GITHUB_REF_NAME \
            .
      - name: Publish image
        run: docker push $IMAGE_NAME:$GITHUB_REF_NAME
