name: Build declarative-postgres-backrest

on:
  push:
    tags:
      - '*_*_v*'

env:
  IMAGE_NAME: ghcr.io/jptrs93/declarative-postgres-backrest

jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-go@v6.0.0
        with:
          go-version-file: declarative-postgres-backrest/go.mod
      - name: Test Go packages
        run: go test ./...
        working-directory: declarative-postgres-backrest
      - name: Build test image
        run: docker build --platform linux/amd64 -f declarative-postgres-backrest/Dockerfile -t declarative-postgres-backrest:test .
      - name: Run integration test
        run: declarative-postgres-backrest/tests/integration.sh declarative-postgres-backrest:test

  publish:
    needs: test
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: docker/login-action@v3.7.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build --platform linux/amd64 -f declarative-postgres-backrest/Dockerfile \
            -t $IMAGE_NAME:$GITHUB_REF_NAME \
            .
      - name: Publish image
        run: |
          docker push $IMAGE_NAME:$GITHUB_REF_NAME
